imager:
  build: imager/
  volumes:
    - ./imager/:/imager/
  ports:
    - "8001:8000"
comparer:
  build: comparer/
  links:
    - postgres
    - imager
  environment:
    - DATABASE_URL=postgres://postgres:mysecretpassword@postgres/postgres
frontend:
  build: frontend/
  volumes:
    - ./frontend/:/frontend/
  ports:
    - "8000:8000"
  links:
    - postgres
  environment:
    - DATABASE_URL=postgres://postgres:mysecretpassword@postgres/postgres
postgres:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
