# Scan this file for changes every 30 seconds
refresh_rate = 30

# An appender named "stdout" that writes to stdout
[appenders.stdout]
kind = "console"

[root]
level = "info"
appenders = ["stdout"]

[loggers."kitling_imager"]
level = "debug"

[loggers."nickel"]
level = "debug"